name: CI

on:
  pull_request:
  workflow_call:
    inputs:
      run-security:
        type: boolean
        default: true
      run-release:
        type: boolean
        default: true

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # ---------------------------------------------------------------------------
  # Quality
  # ---------------------------------------------------------------------------

  quality:
    uses: wphillipmoore/standard-actions/.github/workflows/ci-quality.yml@v1.5
    with:
      language: python
      versions: '["3.14"]'

  test:
    uses: wphillipmoore/standard-actions/.github/workflows/ci-test.yml@v1.5
    with:
      language: python
      versions: '["3.14"]'

  audit:
    uses: wphillipmoore/standard-actions/.github/workflows/ci-audit.yml@v1.5
    with:
      language: python
      versions: '["3.14"]'

  # ---------------------------------------------------------------------------
  # Security and standards
  # ---------------------------------------------------------------------------

  security:
    uses: wphillipmoore/standard-actions/.github/workflows/ci-security.yml@v1.5
    with:
      language: python
      run-standards: ${{ inputs.run-release || true }}
      run-security: ${{ inputs.run-security || true }}
    permissions:
      contents: read
      security-events: write

  # ---------------------------------------------------------------------------
  # Release
  # ---------------------------------------------------------------------------

  release:
    uses: wphillipmoore/standard-actions/.github/workflows/ci-release.yml@v1.5
    with:
      language: python
      run-release: ${{ inputs.run-release != false }}
